version: 2
jobs:
  test:
    docker:
      - image: rust:1.25
    steps:
      - checkout
      - run:
          name: cargo test
          command: |
            cargo test
  check_format:
    docker:
      - image: rust:1.25
    steps:
      - checkout
      - run: test -z "$(cargo fmt --all -- --write-mode=diff)"

workflows:
  version: 2
  tests:
    jobs:
      - test
      - check_format
